### ISSUE TITLE
Arg parsing error (Cannot read property 'indexOf' of undefined)

### ISSUE THREAD

**Issue by franciscolourenco** [khaosdoctor/gotql#33]
**Describe the bug**
Null arg values are not supported (Cannot read property 'indexOf' of undefined)

**To Reproduce**
```js
  return gotQl.mutation('https://example.com', {
    operation: {
      name: 'update_users',
      args: {
        where: {id: {_eq: userId}},
        _set: {name: null},
      },
      fields: ['affected_rows'],
    },
  })
```

**Current behavior**
```
Runner error: Error when executing query: Parse error: Failed to parse operation "update_users" => Cannot read property 'indexOf' of undefined
```

**Expected behavior**
`null` values should be supported.

**Comment by khaosdoctor** [comment]
Thanks for reporting, will fix it ASAP

**Comment by franciscolourenco** [comment]
Thanks for answering! Just to clarify, should I look for another library in the meanwhile?

**Comment by khaosdoctor** [comment]
I'll try to fix it today, I need to find the cause for now but I think this is a pretty simple issue

**Comment by khaosdoctor** [comment]
Ok, found the error. The problem was in the arg parsing, it was checking to see if it was a variable with `indexOf` but passing a number instead so I check before if it is a string.

The `null` was also a problem, so I created a new logic to check for null arg values which should short-circuit as soon as it finds a null arg and returns `'null'` as string to be put in the query

**Comment by franciscolourenco** [comment]
thanks, it works 👍
